#!/usr/bin/env python3

import argparse
import json
import os

from utils import common as c

parser = argparse.ArgumentParser(description='check sum of slots',
                                prefix_chars='-')
parser.add_argument('-ln', '--lastn',
                    default=1, type=int, required=True,
                    help='last n slots to be searched')
parser.add_argument('-n', '--num-cores',
                    default=1, type=int, required=True,
                    help='core number to be searched')
opt = parser.parse_args()
curdir = os.getcwd()

jfile = f'{opt.lastn}period.json'

s = c.extract_samples_raw_json(curdir, opt.num_cores, opt.lastn)


with open(jfile, 'r') as f:
    d = json.load(f)
    print(json.dumps(d, indent=0,separators=(' ', ':')))