#!/usr/bin/env python3

import re
import argparse
import json
import os
from utils.target_stats import *

parser = argparse.ArgumentParser(description='check sum of slots',
                                prefix_chars='-')
parser.add_argument('-j', '--json', default='./4period.json',
                    help='stats.txt to be converted')

opt = parser.parse_args()
curdir = os.getcwd()
jfile = os.path.join(curdir, opt.json)

patterns = {}

targets = llc_miss_only

meta_pattern = re.compile('.*\((\w.+)\).*')
for t in targets:
    meta = meta_pattern.search(t).group(1)
    patterns[meta] = re.compile(t+r'\b')

with open(jfile, 'r') as f:
    d = json.load(f)
    print(json.dumps(d, indent=0,separators=(' ', ':')))
    # for k in d:
    #     for p in patterns:
    #         m = patterns[p].search(k)
    #         if m:
    #             d[k] = m.group(1)
    #             break


