# test_prefix = 'newdb-'
base_dir_format = '/nfs/home/zhangchuanqi/lvna/for_xs/catlog/{}single-profiling/'
conf_20M = {
    'test_prefix': 'newdb-',
    'cache_work_names': [
                            'gcc_g23',
                            'sphinx3',
                            'soplex_pds',
                            'xalancbmk',
                            'mcf',
                            'cactusADM',
                            'lbm',
                            'gcc_200',
                            'gcc_cpdecl',
                            'omnetpp',
                            'gcc_scilab',
                            'astar_biglakes',
                        ],
    'cache_work_90perfways': {
                                'gcc_g23': 7,
                                'sphinx3': 4,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 5,
                                'lbm': 5,
                                'gcc_200': 3,
                                'gcc_cpdecl': 2,
                                'omnetpp': 2,
                                'gcc_scilab': 2,
                                'astar_biglakes': 1,
                            },
    'cache_work_95perfways' : {
                                'gcc_g23': 7,
                                'sphinx3': 5,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 5,
                                'lbm': 7,
                                'gcc_200': 5,
                                'gcc_cpdecl': 4,
                                'omnetpp': 4,
                                'gcc_scilab': 3,
                                'astar_biglakes': 1,
                            },
    'cache_work_fullways' : {
                                'gcc_g23': 8,
                                'sphinx3': 8,
                                'soplex_pds': 8,
                                'xalancbmk': 8,
                                'mcf': 8,
                                'cactusADM': 8,
                                'lbm': 8,
                                'gcc_200': 8,
                                'gcc_cpdecl': 8,
                                'omnetpp': 8,
                                'gcc_scilab': 8,
                                'astar_biglakes': 8,
                            },
}
conf_50M = {
    'test_prefix': 'newdb50M-',
    'cache_work_names': [
                            'gcc_g23',
                            'sphinx3',
                            'soplex_pds',
                            'xalancbmk',
                            'mcf',
                            'cactusADM',
                            'lbm',
                            'gcc_200',
                            'gcc_cpdecl',
                            'omnetpp',
                            'gcc_scilab',
                            'astar_biglakes',
                        ],
    'cache_work_90perfways': {
                                'gcc_g23': 7,
                                'sphinx3': 4,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 5,
                                'lbm': 5,
                                'gcc_200': 3,
                                'gcc_cpdecl': 2,
                                'omnetpp': 2,
                                'gcc_scilab': 2,
                                'astar_biglakes': 1,
                            },
    'cache_work_95perfways' : {
                                'gcc_g23': 7,
                                'sphinx3': 5,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 6,
                                'lbm': 7,
                                'gcc_200': 4,
                                'gcc_cpdecl': 3,
                                'omnetpp': 4,
                                'gcc_scilab': 3,
                                'astar_biglakes': 5,
                            },
    'cache_work_fullways' : {
                                'gcc_g23': 8,
                                'sphinx3': 8,
                                'soplex_pds': 8,
                                'xalancbmk': 8,
                                'mcf': 8,
                                'cactusADM': 8,
                                'lbm': 8,
                                'gcc_200': 8,
                                'gcc_cpdecl': 8,
                                'omnetpp': 8,
                                'gcc_scilab': 8,
                                'astar_biglakes': 8,
                            },
}

# use_conf = conf_20M
use_conf = conf_50M
# cache_work_names = [
#     'gcc_g23',
#     'sphinx3',
#     'soplex_pds',
#     'xalancbmk',
#     'mcf',
#     'cactusADM',
#     'gcc_200',
#     'lbm',
#     'gcc_cpdecl',
#     'astar_biglakes',
#     'gcc_scilab',
#     'omnetpp',
# ]
# cache_work_90perfways = {
#     'gcc_g23': 8,
#     'sphinx3': 4,
#     'soplex_pds': 7,
#     'xalancbmk': 7,
#     'mcf': 7,
#     'cactusADM': 5,
#     'gcc_200': 4,
#     'lbm': 5,
#     'gcc_cpdecl': 3,
#     'astar_biglakes': 1,
#     'gcc_scilab': 2,
#     'omnetpp': 2,
# }
# cache_work_95perfways = {
#     'gcc_g23': 8,
#     'sphinx3': 5,
#     'soplex_pds': 8,
#     'xalancbmk': 8,
#     'mcf': 8,
#     'cactusADM': 5,
#     'gcc_200': 5,
#     'lbm': 7,
#     'gcc_cpdecl': 3,
#     'astar_biglakes': 5,
#     'gcc_scilab': 3,
#     'omnetpp': 4,
# }
# cache_work_fullways = {
#     'gcc_g23': 8,
#     'sphinx3': 8,
#     'soplex_pds': 8,
#     'xalancbmk': 8,
#     'mcf': 8,
#     'cactusADM': 8,
#     'gcc_200': 8,
#     'lbm': 8,
#     'gcc_cpdecl': 8,
#     'astar_biglakes': 8,
#     'gcc_scilab': 8,
#     'omnetpp': 8,
# }