# test_prefix = 'newdb-'
base_dir_format = '/nfs/home/zhangchuanqi/lvna/for_xs/catlog/{}single-profiling/'
conf_20M = {
    'test_prefix': 'newdb-',
    'cache_work_names': [
                            'gcc_g23',
                            'sphinx3',
                            'soplex_pds',
                            'xalancbmk',
                            'mcf',
                            'cactusADM',
                            'lbm',
                            'gcc_200',
                            'gcc_cpdecl',
                            'omnetpp',
                            'gcc_scilab',
                            'astar_biglakes',
                        ],
    'cache_work_90perfways': {
                                'gcc_g23': 7,
                                'sphinx3': 4,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 5,
                                'lbm': 5,
                                'gcc_200': 3,
                                'gcc_cpdecl': 2,
                                'omnetpp': 2,
                                'gcc_scilab': 2,
                                'astar_biglakes': 1,
                            },
    'cache_work_95perfways' : {
                                'gcc_g23': 7,
                                'sphinx3': 5,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 5,
                                'lbm': 7,
                                'gcc_200': 5,
                                'gcc_cpdecl': 4,
                                'omnetpp': 4,
                                'gcc_scilab': 3,
                                'astar_biglakes': 1,
                            },
    'cache_work_fullways' : {
                                'gcc_g23': 8,
                                'sphinx3': 8,
                                'soplex_pds': 8,
                                'xalancbmk': 8,
                                'mcf': 8,
                                'cactusADM': 8,
                                'lbm': 8,
                                'gcc_200': 8,
                                'gcc_cpdecl': 8,
                                'omnetpp': 8,
                                'gcc_scilab': 8,
                                'astar_biglakes': 8,
                            },
}
conf_50M = {
    'test_prefix': 'newdb50M-',
    'cache_work_names': [
                            'gcc_g23',
                            'sphinx3',
                            'soplex_pds',
                            'xalancbmk',
                            'mcf',
                            'cactusADM',
                            'lbm',
                            'gcc_200',
                            'gcc_cpdecl',
                            'omnetpp',
                            'gcc_scilab',
                            'astar_biglakes',
                        ],
    'cache_work_90perfways': {
                                'gcc_g23': 7,
                                'sphinx3': 4,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 5,
                                'lbm': 5,
                                'gcc_200': 3,
                                'gcc_cpdecl': 2,
                                'omnetpp': 2,
                                'gcc_scilab': 2,
                                'astar_biglakes': 1,
                            },
    'cache_work_95perfways' : {
                                'gcc_g23': 7,
                                'sphinx3': 5,
                                'soplex_pds': 7,
                                'xalancbmk': 7,
                                'mcf': 7,
                                'cactusADM': 6,
                                'lbm': 7,
                                'gcc_200': 4,
                                'gcc_cpdecl': 3,
                                'omnetpp': 4,
                                'gcc_scilab': 3,
                                'astar_biglakes': 5,
                            },
        'cache_work_95perfmax8ways' : {
                                'gcc_g23': 8,
                                'sphinx3': 5,
                                'soplex_pds': 7,
                                'xalancbmk': 8,
                                'mcf': 8,
                                'cactusADM': 6,
                                'lbm': 7,
                                'gcc_200': 4,
                                'gcc_cpdecl': 3,
                                'omnetpp': 4,
                                'gcc_scilab': 3,
                                'astar_biglakes': 5,
                            },
    'cache_work_fullways' : {
                                'gcc_g23': 8,
                                'sphinx3': 8,
                                'soplex_pds': 8,
                                'xalancbmk': 8,
                                'mcf': 8,
                                'cactusADM': 8,
                                'lbm': 8,
                                'gcc_200': 8,
                                'gcc_cpdecl': 8,
                                'omnetpp': 8,
                                'gcc_scilab': 8,
                                'astar_biglakes': 8,
                            },
    'grow_last_target': {
                            'gcc_g23':7144,
                            'sphinx3':5100,
                            'soplex_pds':12970,
                            'xalancbmk':12791,
                            'mcf':13415,
                            'cactusADM':5258,
                            'lbm':7433,
                            'gcc_200':4183,
                            'gcc_cpdecl':5394,
                            'omnetpp':5490,
                            'gcc_scilab':7118,
                            'astar_biglakes':1650,
                        },
}

conf_ship50M = {
    'test_prefix': 'ship50M-',
    'cache_work_names': [
                        "astar_biglakes",
                        "cactusADM",
                        "gcc_200",
                        "gcc_cpdecl",
                        "gcc_g23",
                        "gcc_scilab",
                        "gcc_typeck",
                        "lbm",
                        "libquantum",
                        "mcf",
                        "omnetpp",
                        "soplex_pds",
                        "sphinx3",
                        "xalancbmk",
                        ],
    'cache_work_90perfways': {
                                "astar_biglakes":1,
                                "cactusADM":4,
                                "gcc_200":3,
                                "gcc_cpdecl":3,
                                "gcc_g23":7,
                                "gcc_scilab":2,
                                "gcc_typeck":2,
                                "lbm":2,
                                "libquantum":1,
                                "mcf":4,
                                "omnetpp":1,
                                "soplex_pds":6,
                                "sphinx3":5,
                                "xalancbmk":4,
                            },
    'cache_work_95perfways' : {
                                "astar_biglakes":4,
                                "cactusADM":6,
                                "gcc_200":4,
                                "gcc_cpdecl":4,
                                "gcc_g23":7,
                                "gcc_scilab":3,
                                "gcc_typeck":4,
                                "lbm":5,
                                "libquantum":6,
                                "mcf":6,
                                "omnetpp":4,
                                "soplex_pds":7,
                                "sphinx3":6,
                                "xalancbmk":7,
                            },
    'cache_work_fullways' : {
                                "astar_biglakes":8,
                                "cactusADM":8,
                                "gcc_200":8,
                                "gcc_cpdecl":8,
                                "gcc_g23":8,
                                "gcc_scilab":8,
                                "gcc_typeck":8,
                                "lbm":8,
                                "libquantum":8,
                                "mcf":8,
                                "omnetpp":8,
                                "soplex_pds":8,
                                "sphinx3":8,
                                "xalancbmk":8,
                            },
}

conf_100M = {
    'test_prefix': 'rrip100M-',
    'cache_work_names': [
                            'astar_biglakes',
                            'bzip2_chicken',
                            'cactusADM',
                            'gcc_200',
                            'gcc_cpdecl',
                            'gcc_g23',
                            'gcc_scilab',
                            'gcc_typeck',
                            'lbm',
                            'mcf',
                            'omnetpp',
                            'perlbench_checkspam',
                            'soplex_pds',
                            'soplex_ref',
                            'sphinx3',
                            'xalancbmk',
                        ],
    'cache_work_90perfways': {
                                'astar_biglakes':3,
                                'bzip2_chicken':2,
                                'cactusADM':5,
                                'gcc_200':3,
                                'gcc_cpdecl':2,
                                'gcc_g23':7,
                                'gcc_scilab':2,
                                'gcc_typeck':4,
                                'lbm':5,
                                'mcf':7,
                                'omnetpp':2,
                                'perlbench_checkspam':2,
                                'soplex_pds':7,
                                'soplex_ref':3,
                                'sphinx3':4,
                                'xalancbmk':7,
                            },
    'cache_work_95perfways' : {
'astar_biglakes':5,
'bzip2_chicken':3,
'cactusADM':6,
'gcc_200':4,
'gcc_cpdecl':3,
'gcc_g23':7,
'gcc_scilab':3,
'gcc_typeck':5,
'lbm':7,
'mcf':7,
'omnetpp':4,
'perlbench_checkspam':5,
'soplex_pds':7,
'soplex_ref':5,
'sphinx3':5,
'xalancbmk':7,
                            },
    'cache_work_fullways' : {
'astar_biglakes':8,
'bzip2_chicken':8,
'cactusADM':8,
'gcc_200':8,
'gcc_cpdecl':8,
'gcc_g23':8,
'gcc_scilab':8,
'gcc_typeck':8,
'lbm':8,
'mcf':8,
'omnetpp':8,
'perlbench_checkspam':8,
'soplex_pds':8,
'soplex_ref':8,
'sphinx3':8,
'xalancbmk':8,
                            },
}


# use_conf = conf_20M
use_conf = conf_50M
# cache_work_names = [
#     'gcc_g23',
#     'sphinx3',
#     'soplex_pds',
#     'xalancbmk',
#     'mcf',
#     'cactusADM',
#     'gcc_200',
#     'lbm',
#     'gcc_cpdecl',
#     'astar_biglakes',
#     'gcc_scilab',
#     'omnetpp',
# ]
# cache_work_90perfways = {
#     'gcc_g23': 8,
#     'sphinx3': 4,
#     'soplex_pds': 7,
#     'xalancbmk': 7,
#     'mcf': 7,
#     'cactusADM': 5,
#     'gcc_200': 4,
#     'lbm': 5,
#     'gcc_cpdecl': 3,
#     'astar_biglakes': 1,
#     'gcc_scilab': 2,
#     'omnetpp': 2,
# }
# cache_work_95perfways = {
#     'gcc_g23': 8,
#     'sphinx3': 5,
#     'soplex_pds': 8,
#     'xalancbmk': 8,
#     'mcf': 8,
#     'cactusADM': 5,
#     'gcc_200': 5,
#     'lbm': 7,
#     'gcc_cpdecl': 3,
#     'astar_biglakes': 5,
#     'gcc_scilab': 3,
#     'omnetpp': 4,
# }
# cache_work_fullways = {
#     'gcc_g23': 8,
#     'sphinx3': 8,
#     'soplex_pds': 8,
#     'xalancbmk': 8,
#     'mcf': 8,
#     'cactusADM': 8,
#     'gcc_200': 8,
#     'lbm': 8,
#     'gcc_cpdecl': 8,
#     'astar_biglakes': 8,
#     'gcc_scilab': 8,
#     'omnetpp': 8,
# }